CREATE TABLE categories (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_order int,
    name text NOT NULL,
    description text
);

CREATE TABLE boards (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category_id int REFERENCES categories (id),
  parent_id int REFERENCES boards (id),
  board_order int,
  name text NOT NULL,
  description text,
  icon varchar(20)
);

CREATE TABLE message_icons (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title text,
  filename text,
  icon_order int
);

INSERT INTO message_icons (filename, title, icon_order)
VALUES
('xx', 'Standard', 0),
('thumbup', 'Thumb Up', 1),
('thumbdown', 'Thumb Down', 2),
('exclamation', 'Exclamation point', 3),
('question', 'Question mark', 4),
('lamp', 'Lamp', 5),
('smiley', 'Smiley', 6),
('angry', 'Angry', 7),
('cheesy', 'Cheesy', 8),
('grin', 'Grin', 9),
('sad', 'Sad', 10),
('wink', 'Wink', 11);

